version: "3.6"

services:
 sut:
  build:
   context: ./archtec/test
   args:
    ENGINE_VERSION: ${ENGINE_VERSION:-5.7.0}
  user: root
  volumes:
    - "./:/root/.minetest/worlds/world/worldmods/archtec/"
    - "world_data:/root/.minetest/worlds/world"
    - "./archtec/test/world.mt:/root/.minetest/worlds/world/world.mt"
    - "./archtec/test/minetest.conf:/minetest.conf"
  ports:
    - "30000:30000/udp"

volumes:
  world_data: {}