name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        ENGINE_VERSION: [5.6.0, 5.7.0, latest]

    steps:
    - uses: actions/checkout@v3
    - name: test
      run: docker-compose up --exit-code-from sut